Repository pion/webrtc, pull requests merged in 2019-03, with the labels that each got.

#463 Don't allow RTP codecs that violate RFC7587
  examples/save-to-disk/main.go
  mediaengine.go
Labels: review

#465 Update LocalInterfaces() to comply with spec
  internal/ice/util.go
Labels: review

#474 Provide easy example of video without browser
  examples/gstreamer-send-offer/README.md
  examples/gstreamer-send-offer/main.go
  examples/internal/signal/http.go
  examples/sfu/main.go
Labels: review

#483 Remove pkg/errors dependency
  datachannel.go
  datachannel_ortc_test.go
  dtlstransport.go
  go.mod
  internal/ice/agent.go
  internal/ice/errors.go
  internal/ice/url_test.go
  internal/util/util.go
  peerconnection.go
  quictransport_test.go
  rtptransceiver.go
  signalingstate.go
Labels: review

#489 Update janus-gateway/video-room with keepalive
  examples/janus-gateway/README.md
  examples/janus-gateway/video-room/main.go
Labels: review

#488 Fix deadlock in DTLS shutdown
  internal/mux/mux.go
  peerconnection.go
  peerconnection_media_test.go
  peerconnection_test.go
Labels: review

#496 Update to use new RTCP API
  go.mod
  go.sum
  rtpreceiver.go
  rtpsender.go
Labels: review

#492 Examples: serve WASM examples locally
  examples/data-channels-close/jsfiddle/demo.css
  examples/data-channels-close/jsfiddle/demo.html
  examples/data-channels-create/jsfiddle/demo.css
  examples/data-channels-create/jsfiddle/demo.html
  examples/data-channels/jsfiddle/demo.css
  examples/data-channels/jsfiddle/demo.html
  examples/example.html
  examples/examples.go
  examples/examples.json
  examples/gstreamer-receive/jsfiddle/demo.css
  examples/gstreamer-receive/jsfiddle/demo.html
  examples/gstreamer-send/jsfiddle/demo.css
  examples/gstreamer-send/jsfiddle/demo.html
  examples/index.html
  examples/save-to-disk/jsfiddle/demo.css
  examples/save-to-disk/jsfiddle/demo.html
  examples/sfu/jsfiddle/demo.css
  examples/sfu/jsfiddle/demo.html
  examples/vendor-wasm/golang.org/LICENSE
  examples/vendor-wasm/golang.org/PATENTS
  examples/vendor-wasm/golang.org/VERSION
  examples/vendor-wasm/golang.org/misc/wasm/go_js_wasm_exec
  examples/vendor-wasm/golang.org/misc/wasm/wasm_exec.html
  examples/vendor-wasm/golang.org/misc/wasm/wasm_exec.js
  examples/vendor-wasm/readme.md
Labels: WASM, review

#497 Check for nil Receiver in PeerConnection.AddTrack
  peerconnection.go
Labels: review

#484 Hardcoded header in IVFWriter
  examples/save-to-disk/README.md
  examples/save-to-disk/main.go
  pkg/media/ivfwriter/ivfwriter.go
Labels: review

#479 Add JavaScript/WASM bindings
  .gitignore
  README.md
  constants.go
  datachannel.go
  datachannel_js.go
  datachannelmessage.go
  dtlstransport.go
  examples/data-channels/jsfiddle/main.go
  icetransport.go
  js_utils.go
  peerconnection.go
  peerconnection_js.go
  quictransport.go
  rtpreceiver.go
  rtpsender.go
  rtptransceiver.go
  sctptransport.go
  track.go
Labels: WASM

#502 WASM: Document WASM support
  README.md
  examples/README.md
Labels: review

#467 Issue 460
  icegatherer.go
  internal/ice/agent.go
  internal/ice/networktype.go
  internal/ice/transport_test.go
  internal/ice/util.go
  networktype.go
  networktype_test.go
  peerconnection.go
  settingengine.go
Labels: review

#480 Optimize reads with buffering
  go.mod
  go.sum
  internal/ice/agent.go
  internal/ice/candidate.go
  internal/ice/transport.go
  internal/mux/endpoint.go
  internal/mux/mux.go
  internal/mux/mux_test.go
  lossy_stream.go
  peerconnection.go
  pkg/media/opuswriter/opuswriter_test.go
  rtpreceiver.go
  rtpsender.go
  track.go
Labels: review

#504 Test WASM bindings in a Node.js environment
  .gitignore
  .travis.yml
  api_test.go
  certificate_test.go
  datachannel_go_test.go
  datachannel_js.go
  datachannel_js_test.go
  datachannel_ortc_test.go
  datachannel_test.go
  icegatherer_test.go
  package.json
  peerconnection_close_go_test.go
  peerconnection_close_js_test.go
  peerconnection_go_test.go
  peerconnection_js.go
  peerconnection_js_test.go
  peerconnection_media_test.go
  peerconnection_test.go
  quictransport_test.go
  test-wasm/LICENSE
  test-wasm/go_js_wasm_exec
  test-wasm/node_shim.js
  track_test.go
  yarn.lock
Labels: WASM, review

#524 Change public DataChannel props to methods
  datachannel.go
  datachannel_go_test.go
  peerconnection.go
  sctptransport.go
Labels: review

#527 Change PeerConnection public props to methods
  peerconnection_go_test.go
  peerconnection_test.go
Labels: review

#528 Combine some tests for Go and Wasm
  datachannel_go_test.go
  datachannel_js_test.go
  datachannel_test.go
  peerconnection_close_js_test.go
  peerconnection_close_test.go
Labels: review

#530 Add link to Wasm wiki page in README
  README.md
Labels: review

#532 Bump pions/sctp and pions/dtls
  go.mod
  go.sum
Labels: review

#536 Add feedback support to SDP generation.
  mediaengine.go
  peerconnection.go
  rtcpfeedback.go
Labels: review

#533 Run golangci-lint on examples
  .travis.yml
  examples/data-channels-close/main.go
  examples/data-channels-create/main.go
  examples/data-channels-detach-create/main.go
  examples/data-channels-detach/main.go
  examples/data-channels/main.go
  examples/examples.go
  examples/gstreamer-receive/main.go
  examples/internal/gstreamer-sink/gst.go
  examples/internal/gstreamer-src/gst.go
  examples/janus-gateway/streaming/main.go
  examples/ortc/main.go
  examples/pion-to-pion/answer/main.go
  examples/pion-to-pion/offer/main.go
  examples/save-to-disk/main.go
  examples/sfu-minimal/main.go
  examples/sfu-ws/room.go
  examples/sfu-ws/web.go
Labels: review

#544 Check Node.js version in go_js_wasm_exec script
  test-wasm/go_js_wasm_exec
Labels: review

#547 Rewrite examples to avoid onnegotiationneeded
  examples/examples.json
  examples/gstreamer-receive/README.md
  examples/gstreamer-receive/jsfiddle/demo.js
  examples/save-to-disk/README.md
  examples/save-to-disk/jsfiddle/demo.js
  examples/sfu-minimal/README.md
  examples/sfu-minimal/jsfiddle/demo.js
  examples/sfu-ws/go.mod
  examples/sfu-ws/go.sum
  examples/sfu-ws/sfu.html
Labels: review

#546 Add ICE candidate event handlers
  datachannel_go_test.go
  examples/data-channels/jsfiddle/main.go
  examples/data-channels/main.go
  js_utils.go
  peerconnection.go
  peerconnection_go_test.go
  peerconnection_js.go
  peerconnection_js_test.go
  peerconnection_test.go
Labels: review

#550 Move ICE out of tree
  configuration.go
  configuration_js.go
  go.mod
  go.sum
  icecandidate.go
  icecandidate_test.go
  icegatherer.go
  iceserver.go
  iceserver_js.go
  iceserver_test.go
  icetransport.go
  icetransportstate.go
  icetransportstate_test.go
  internal/ice/agent.go
  internal/ice/agent_test.go
  internal/ice/candidate.go
  internal/ice/candidatepair.go
  internal/ice/candidaterelatedaddress.go
  internal/ice/candidatetype.go
  internal/ice/errors.go
  internal/ice/ice.go
  internal/ice/ice_test.go
  internal/ice/networktype.go
  internal/ice/networktype_test.go
  internal/ice/transport.go
  internal/ice/transport_test.go
  internal/ice/url.go
  internal/ice/url_test.go
  internal/ice/util.go
  peerconnection.go
  peerconnection_go_test.go
  settingengine.go
Labels: review

#554 Let sfu-ws example uses latest webrtc codes And introduce prommods
  examples/sfu-ws/go.mod
  examples/sfu-ws/go.sum
  examples/sfu-ws/main.go
Labels: review

#564 Minor test re-organization
  icetransport_test.go
  peerconnection_media_test.go
Labels: review

#543 Don't notify users via Track of ICE errors
  dtlstransport.go
  go.mod
  go.sum
  peerconnection.go
  peerconnection_media_test.go
  rtpsender.go
Labels: review

#567 Rename SendRTCP -> WriteRTCP
  examples/gstreamer-receive/main.go
  examples/save-to-disk/main.go
  examples/sfu-minimal/main.go
  examples/sfu-ws/go.sum
  examples/sfu-ws/room.go
  peerconnection.go
  peerconnection_js.go
  peerconnection_media_test.go
Labels: review

#568 Rename media.Writer AddPacket -> WriteRTP
  examples/janus-gateway/streaming/main.go
  examples/save-to-disk/main.go
  pkg/media/ivfwriter/ivfwriter.go
  pkg/media/ivfwriter/ivfwriter_test.go
  pkg/media/media.go
  pkg/media/opuswriter/opuswriter.go
  pkg/media/opuswriter/opuswriter_test.go
Labels: review

#514 Return io.EOF when reading/writing media
  peerconnection.go
  peerconnection_media_test.go
  rtpreceiver.go
  rtpsender.go
  track.go
  track_test.go
Labels: review

#570 Don't iterate Transceivers without lock
  peerconnection.go
Labels: review

#573 Don't allow answer without RemoteDescription
  peerconnection.go
  peerconnection_go_test.go
Labels: review
